service: product-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1

  environment:
    PG_HOST: lesson4.czoz6duffqoz.eu-central-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: lesson4
    PG_USERNAME: postgres
    PG_PASSWORD:

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  products:
    handler: handler.products
    events:
      - http:
          path: products
          method: get

  productNew:
    handler: handler.productNew
    events:
      - http:
          path: products
          method: post

  productById:
    handler: handler.productById
    events:
      - http:
          path: products/{productId}
          method: get
          request:
            parameters:
              paths:
                productId: true