service: import-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::nodejs-products-bucket"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::nodejs-products-bucket/*"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - "arn:aws:sqs:eu-central-1:414456242917:catalogItemsQueue"

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          request:
            parameters:
              querystrings:
                name: true
          cors: true
          authorizer:
            name: basicAuthorizer
            arn: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:authorization-service-dev-basicAuthorizer"
            resultTtlInSeconds: 0
            type: token
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: nodejs-products-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

